### PR TITLE
Fix lowercase in library title

### PR DESCRIPTION
**Pull request by otacke**

### CODE REVIEW

**Comment by fnoks** [comment]
For consistency with other content types, I believe we should keep the capitalized title. Any special reason you changed this?

**Comment by otacke** [comment]
@fnoks I agree about consistency and capitalization. That's why I changed it to "Image **C**hoice". It currently is "Image **c**hoice" :-)

**Comment by fnoks** [comment]
:laughing:  Sorry, I misread your commit. Then I absolutely agree :+1:

**Comment by otacke** [comment]
@fnoks I guess I should improve my pull request title writing skills :sweat_smile:

**Comment by fnoks** [comment]
@otacke I think we can blame my reading skills for this one :eyeglasses:

**Pull request merged**
